name: Deploy plugin to WordPress.org

on:
  release:
    types: [published]

permissions:
  contents: read
  deployments: write

jobs:
  deploy:
    name: Deploy updates
    runs-on: ubuntu-latest
    environment: wp.org plugin

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: WordPress.org plugin update
        uses: 10up/action-wordpress-plugin-deploy@stable
        env:
          SVN_USERNAME: ${{ secrets.WORDPRESSORG_SVN_USERNAME }}
          SVN_PASSWORD: ${{ secrets.WORDPRESSORG_SVN_PASSWORD }}
          SLUG: glotpress
